In [729]:
from PIL import Image
import numpy as np
from tqdm import tqdm

block_size = 8

## 根据协议反序列化数据

In [730]:
import pickle

# Read from file
with open('output.pkl', 'rb') as f:
    my_dict = pickle.load(f)
# my_dict = {'huffman_code_y'.encode(): huffman_code_y, 'y'.encode(): data_y, 'huffman_code_cb'.encode(): huffman_code_cb, 
#            'cb'.encode(): data_cb, 'huffman_code_cr'.encode(): huffman_code_cr, 'cr'.encode(): data_cr}
huffman_code_y = my_dict['huffman_code_y']
huffman_code_cb = my_dict['huffman_code_cb']
huffman_code_cr = my_dict['huffman_code_cr']
data_y = my_dict['y']
data_cb = my_dict['cb']
data_cr = my_dict['cr']


In [731]:
data_cb

bitarray('001100111111101010001001000011001111110101000100100001100111111010100010010000110011111101010001001001111110011111101010001001000011001111110101000100100001100111111010100010000100111111001111110101111101000010011110101010010100010101101111111101111100101000101001101001111101110100011111101010011000000001010011110001100110101001000000000001011101101011111111011111011110001010001010000110011111101011111010010011111100111111010100010010000110011111101011111010010000010110010101111101000010001010001010101111011101101011011111100011111011110100111101010111001010011101001010001010011101111100100111101010101111010101101111111101111100101000101001111110011111101011111010000100001100111111010100010010011111100111111010111110100001000011001111111010100010010000110010010101000100001000011001001101010001001000011001111110101000100100001100111111010100010010011111100111111010100010000100111101010101111101011111010000100111101010101111101011111010000100111101010101111101011111010000100111

## 哈夫曼解码

In [732]:
from bitarray import bitarray

def decode_huffman(data, huffman_code):
    flipped_huffman_code = {v.to01(): k for k, v in huffman_code.items()}
    decoded_data = []
    current_code = ''
    i = 0
    for bit in data:
        current_code += str(bit)
        if current_code in flipped_huffman_code.keys():
            decoded_data.append(flipped_huffman_code[current_code])
            #print(current_code)
            current_code = ''
            #print('decoded')
        i = i+1
    #print("----------------------------------")
    return decoded_data

In [733]:
# perform the huffman decoding
runlen_y = decode_huffman(data_y, huffman_code_y)
runlen_cb = decode_huffman(data_cb, huffman_code_cb)
runlen_cr = decode_huffman(data_cr, huffman_code_cr)


In [734]:
runlen_y

[(0, -21.0),
 (1, -28.0),
 (0, -24.0),
 (5, -24.0),
 (0, -19.0),
 (9, -14.0),
 (0, -7.0),
 (13, -5.0),
 (0, 0),
 (0, -21.0),
 (1, -28.0),
 (0, -24.0),
 (5, -24.0),
 (0, -19.0),
 (9, -14.0),
 (0, -7.0),
 (13, -5.0),
 (0, 0),
 (0, -21.0),
 (1, -28.0),
 (0, -24.0),
 (5, -24.0),
 (0, -19.0),
 (9, -14.0),
 (0, -7.0),
 (13, -5.0),
 (0, 0),
 (0, -21.0),
 (1, -28.0),
 (0, -24.0),
 (5, -24.0),
 (0, -19.0),
 (9, -14.0),
 (0, -7.0),
 (13, -5.0),
 (0, 0),
 (0, -21.0),
 (1, -28.0),
 (0, -24.0),
 (5, -24.0),
 (0, -19.0),
 (9, -14.0),
 (0, -7.0),
 (13, -5.0),
 (0, 0),
 (0, -21.0),
 (1, -28.0),
 (0, -24.0),
 (5, -24.0),
 (0, -19.0),
 (9, -14.0),
 (0, -7.0),
 (13, -5.0),
 (0, 0),
 (0, -21.0),
 (1, -28.0),
 (0, -24.0),
 (5, -24.0),
 (0, -19.0),
 (9, -14.0),
 (0, -7.0),
 (13, -5.0),
 (0, 0),
 (0, -21.0),
 (1, -28.0),
 (0, -24.0),
 (5, -24.0),
 (0, -19.0),
 (9, -14.0),
 (0, -7.0),
 (13, -5.0),
 (0, 0),
 (0, -21.0),
 (1, -28.0),
 (0, -24.0),
 (5, -24.0),
 (0, -19.0),
 (9, -14.0),
 (0, -7.0),
 (13, -5.0),
 

In [735]:
runlen_cb

[(0, 1.0),
 (1, 2.0),
 (0, 2.0),
 (5, 1.0),
 (0, 1.0),
 (9, 1.0),
 (0, 0),
 (0, 1.0),
 (1, 2.0),
 (0, 2.0),
 (5, 2.0),
 (0, 1.0),
 (9, 1.0),
 (0, 0),
 (0, 1.0),
 (1, 2.0),
 (0, 2.0),
 (5, 2.0),
 (0, 1.0),
 (9, 1.0),
 (0, 0),
 (0, 1.0),
 (1, 2.0),
 (0, 2.0),
 (5, 2.0),
 (0, 1.0),
 (9, 1.0),
 (0, 0),
 (0, 2.0),
 (1, 2.0),
 (0, 2.0),
 (5, 2.0),
 (0, 1.0),
 (9, 1.0),
 (0, 0),
 (0, 1.0),
 (1, 2.0),
 (0, 2.0),
 (5, 2.0),
 (0, 1.0),
 (9, 1.0),
 (0, 0),
 (0, 1.0),
 (1, 2.0),
 (0, 2.0),
 (5, 2.0),
 (0, 1.0),
 (9, 1.0),
 (0, 1.0),
 (0, 0),
 (0, 2.0),
 (1, 2.0),
 (0, 2.0),
 (5, 2.0),
 (0, 2.0),
 (9, 1.0),
 (0, 1.0),
 (0, 0),
 (0, 2.0),
 (1, 3.0),
 (0, 3.0),
 (5, 3.0),
 (0, 2.0),
 (9, 2.0),
 (0, 1.0),
 (13, 1.0),
 (0, 0),
 (0, 4.0),
 (0, -2.0),
 (0, 5.0),
 (0, 3.0),
 (3, -1.0),
 (0, 1.0),
 (0, 3.0),
 (0, 2.0),
 (0, 1.0),
 (0, -1.0),
 (0, 1.0),
 (5, 1.0),
 (0, 1.0),
 (0, 0),
 (0, 1.0),
 (0, 1.0),
 (0, 1.0),
 (0, 1.0),
 (1, 1.0),
 (2, -1.0),
 (0, 2.0),
 (0, 2.0),
 (0, -1.0),
 (8, 1.0),
 (0, 1.0),
 (

In [736]:
runlen_cr

[(0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (2, -1.0),
 (0, -1.0),
 (5, -1.0),
 (0, 0),
 (0, -1.0),
 (1, -1.0),
 (0, -1.0),
 (5, -1.0),
 (0, -1.0),
 (9, -1.0),
 (0, 0),
 (0, -1.0),
 (1, -1.0),
 (0, -1.0),
 (5, -2.0),
 (0, -1.0),
 (9, -1.0),
 (0, -1.0),
 (13, -1.0),
 (0, 0),
 (0, -3.0),
 (0, 1.0),
 (0, -4.0),
 (0, -3.0),
 (0, 1.0),
 (4, -3.0),
 (0, -2.0),
 (0, -1.0),
 (0, 1.0),
 (0, -1.0),
 (4, 1.0),
 (0, -1.0),
 (0, -1.0),
 (0, 0),
 (0, -1.0),
 (0, -1.0),
 (0, -2.0),
 (0, -1.0),
 (1, -1.0),
 (3, -1.0),
 (0, -1.0),
 (0, 0),
 (0, -1.0),
 (1, -1.0),
 (5, -1.0),
 (0, 1.0),
 (0, 1.0),
 (0, -1.0),
 (8, 2.0),
 (0, 1.0),
 (13, 1.0),
 (0, 0),
 (0, -1.0),
 (1, -1.0),
 (6, 1.0),
 (0, 2.0),
 (9, 2.0),
 (0, 1.0),
 (13, 1.0),
 (0, 0),
 (0, -1.0),
 (1, -1.0),
 (17, 1.0),
 (0, 1.0),
 (13, 1.0),
 (0, 0),
 (0, -1.0),
 (1, -2.0),
 (0, -1.0),
 (5, -1.0),
 (0, 0),
 (0, -2.0),
 (0, -1.0),
 (0, -3.0),
 (0, -2.0),
 (4, 1.0),
 (0, -2.0),
 (0, -1.0),
 (9, -1.0),
 (0, 0),
 (0, -1.0),
 (1, -2.0),
 (0, 

## 解游程编码

In [737]:
def inverse_zigzag_block(input):
    h = int(np.sqrt(len(input)))
    result = np.zeros((h, h))
    index = -1
    for i in range(2 * h - 1):
        if i % 2 == 0:
            x = i if i < h else h - 1
            y = 0 if i < h else i - h + 1
            while x >= 0 and y < h:
                index += 1
                result[x][y] = input[index]
                x -= 1
                y += 1
        else:
            x = 0 if i < h else i - h + 1
            y = i if i < h else h - 1
            while x < h and y >= 0:
                index += 1
                result[x][y] = input[index]
                x += 1
                y -= 1
    return result
def inverse_zigzag(input,h,w):
    result = np.zeros((h , w))
    for i in range(0, h, 8):
        for j in range(0, w, 8):
            result[i:i+8,j:j+8] = inverse_zigzag_block(input[i*w+j*8:i*w+j*8+64])
    return result
    
def run_length_decoding(symbols):
    output = []
  
    i = 0
    while i < len(symbols):
        if symbols[i] == (0,0):
            output.extend([0]*(block_size**2 - len(output)%(block_size**2)))
        else:
            output.extend([0]*symbols[i][0])
            output.append(symbols[i][1])
        i += 1
    return output

In [738]:
len(run_length_decoding(runlen_y))/512

512.0

In [739]:
quantized_y = inverse_zigzag(run_length_decoding(runlen_y),512,512)
quantized_cb = inverse_zigzag(run_length_decoding(runlen_cb),256,256)
quantized_cr = inverse_zigzag(run_length_decoding(runlen_cr),256,256)

In [740]:
quantized_y[255:265, 255:265]

array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  6.,  1.,  2., -1.,  0.,  0.,  0.,  0.,  5.],
       [ 0.,  9.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  6.],
       [ 0.,  8.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  5.],
       [ 0.,  8.,  1.,  0., -1.,  0.,  0.,  0.,  0.,  6.],
       [ 0.,  6.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  5.],
       [ 0.,  4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  4.],
       [ 0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.],
       [ 0.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0., -7., -1., -1., -1.,  0.,  0.,  0.,  2.]])

In [741]:
quantized_cb[127:137, 127:137]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -2.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -2.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -2.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -2.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [742]:
quantized_cr[127:137, 127:137]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 4., 0., 0., 0., 0., 0., 0., 0., 5.],
       [0., 5., 0., 0., 0., 0., 0., 0., 0., 6.],
       [0., 4., 0., 0., 0., 0., 0., 0., 0., 5.],
       [0., 4., 0., 0., 0., 0., 0., 0., 0., 5.],
       [0., 3., 0., 0., 0., 0., 0., 0., 0., 4.],
       [0., 2., 0., 0., 0., 0., 0., 0., 0., 2.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 3., 0., 1., 0., 0., 0., 0., 0., 3.]])

## 反量化

In [743]:
standard_quantization_matrix = np.array([
    [16, 11, 10, 16, 24, 40, 51, 61],
    [12, 12, 14, 19, 26, 58, 60, 55],
    [14, 13, 16, 24, 40, 57, 69, 56],
    [14, 17, 22, 29, 51, 87, 80, 62],
    [18, 22, 37, 56, 68, 109, 103, 77],
    [24, 35, 55, 64, 81, 104, 113, 92],
    [49, 64, 78, 87, 103, 121, 120, 101],
    [72, 92, 95, 98, 112, 100, 103, 99]
])
# standard_quantization_matrix = np.ones((8,8))

In [744]:
def dequantize_block(quantized_block, quant_matrix):
    return quantized_block * quant_matrix
    
def apply_dequantization(quantized_image, quant_matrix):
    h, w = quantized_image.shape
    dct_image = np.zeros((h, w))
    for i in range(0, h, 8):
        for j in range(0, w, 8):
            dct_image[i:i+8, j:j+8] = dequantize_block(quantized_image[i:i+8, j:j+8], quant_matrix)

    return dct_image

In [745]:
dct_y = apply_dequantization(quantized_y, standard_quantization_matrix)
dct_cb = apply_dequantization(quantized_cb, standard_quantization_matrix)
dct_cr = apply_dequantization(quantized_cr, standard_quantization_matrix)

In [746]:
dct_y[255:265, 255:265]

array([[  0.,  72.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  72.],
       [  0.,  96.,  11.,  20., -16.,   0.,   0.,   0.,   0.,  80.],
       [  0., 108.,  12.,  14.,   0.,   0.,   0.,   0.,   0.,  72.],
       [  0., 112.,  13.,   0.,   0.,   0.,   0.,   0.,   0.,  70.],
       [  0., 112.,  17.,   0., -29.,   0.,   0.,   0.,   0.,  84.],
       [  0., 108.,  22.,   0.,   0.,   0.,   0.,   0.,   0.,  90.],
       [  0.,  96.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  96.],
       [  0.,  98.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  98.],
       [  0.,  72., -92.,   0.,   0.,   0.,   0.,   0.,   0.,  72.],
       [  0.,   0., -77., -10., -16., -24.,   0.,   0.,   0.,  32.]])

In [747]:
np.set_printoptions(suppress=True, precision=3)

dct_cb[127:137, 127:137]

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., -32.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., -24.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., -28.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., -28.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., -18.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  11.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [748]:
dct_cr[127:137, 127:137]

array([[ 0., 72.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 72.],
       [ 0., 64.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 80.],
       [ 0., 60.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 72.],
       [ 0., 56.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 70.],
       [ 0., 56.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 70.],
       [ 0., 54.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 72.],
       [ 0., 48.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 48.],
       [ 0., 49.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 49.],
       [ 0., 72.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 72.],
       [ 0., 48.,  0., 10.,  0.,  0.,  0.,  0.,  0., 48.]])

## 逆向离散余弦变换

In [749]:
from scipy.fftpack import dct, idct
    

In [750]:
def apply_idct_to_dct_transformed(dct_transformed):
    """Apply DCT to each 8x8 block of the image."""
    h, w = dct_transformed.shape
    img = np.zeros((h, w))

    for i in tqdm(range(0, h, 8)):
        for j in range(0, w, 8):
            img[i:i+8, j:j+8] = idct(dct_transformed[i:i+8, j:j+8],norm='ortho',type=2)
    img+=128
    return img

In [751]:
y = apply_idct_to_dct_transformed(dct_y)
cb = apply_idct_to_dct_transformed(dct_cb)
cr = apply_idct_to_dct_transformed(dct_cr)

100%|████████████████████████████████████████████████████████████████████████████████| 32/32 [00:00<00:00, 3090.79it/s]


In [752]:
y[255:265, 255:265]

array([[178.912, 153.456, 153.456, 153.456, 153.456, 153.456, 153.456,
        153.456, 153.456, 153.456],
       [178.387, 169.922, 171.902, 169.016, 158.22 , 147.185, 147.212,
        159.634, 172.437, 179.098],
       [185.714, 178.536, 173.851, 166.838, 160.887, 158.546, 160.172,
        163.874, 166.766, 155.917],
       [166.437, 173.973, 173.003, 171.209, 168.866, 166.33 , 163.987,
        162.193, 161.223, 170.858],
       [172.811, 163.878, 177.494, 186.542, 177.312, 157.884, 148.654,
        157.702, 171.318, 155.872],
       [170.373, 176.972, 175.33 , 172.295, 168.33 , 164.038, 160.072,
        157.038, 155.395, 131.939],
       [171.578, 161.941, 161.941, 161.941, 161.941, 161.941, 161.941,
        161.941, 161.941, 144.777],
       [128.138, 162.648, 162.648, 162.648, 162.648, 162.648, 162.648,
        162.648, 162.648, 131.263],
       [ 39.   , 108.34 , 115.208, 127.9  , 144.482, 162.43 , 179.012,
        191.703, 198.572, 197.34 ],
       [ 91.057,  70.483, 104.121, 12

In [753]:
np.set_printoptions(threshold=np.inf)
cb[127:137, 127:137]

array([[128.   , 128.   , 128.   , 128.   , 128.   , 128.   , 128.   ,
        128.   , 128.   , 128.   ],
       [128.263, 128.   , 128.   , 128.   , 128.   , 128.   , 128.   ,
        128.   , 128.   , 116.686],
       [126.358, 128.   , 128.   , 128.   , 128.   , 128.   , 128.   ,
        128.   , 128.   , 119.515],
       [132.95 , 128.   , 128.   , 128.   , 128.   , 128.   , 128.   ,
        128.   , 128.   , 124.476],
       [128.   , 128.   , 128.   , 128.   , 128.   , 128.   , 128.   ,
        128.   , 128.   , 118.101],
       [128.   , 128.   , 128.   , 128.   , 128.   , 128.   , 128.   ,
        128.   , 128.   , 121.636],
       [128.   , 128.   , 128.   , 128.   , 128.   , 128.   , 128.   ,
        128.   , 128.   , 128.   ],
       [128.   , 128.   , 128.   , 128.   , 128.   , 128.   , 128.   ,
        128.   , 128.   , 128.   ],
       [128.   , 128.   , 128.   , 128.   , 128.   , 128.   , 128.   ,
        128.   , 128.   , 128.   ],
       [133.657, 133.394, 132.573, 13

In [754]:
cr[127:137, 127:137]

array([[153.456, 153.456, 153.456, 153.456, 153.456, 153.456, 153.456,
        153.456, 153.456, 153.456],
       [150.365, 150.627, 150.627, 150.627, 150.627, 150.627, 150.627,
        150.627, 150.627, 156.284],
       [150.855, 149.213, 149.213, 149.213, 149.213, 149.213, 149.213,
        149.213, 149.213, 153.456],
       [147.799, 147.799, 147.799, 147.799, 147.799, 147.799, 147.799,
        147.799, 147.799, 152.749],
       [147.799, 147.799, 147.799, 147.799, 147.799, 147.799, 147.799,
        147.799, 147.799, 152.749],
       [147.092, 147.092, 147.092, 147.092, 147.092, 147.092, 147.092,
        147.092, 147.092, 153.456],
       [144.971, 144.971, 144.971, 144.971, 144.971, 144.971, 144.971,
        144.971, 144.971, 144.971],
       [145.324, 145.324, 145.324, 145.324, 145.324, 145.324, 145.324,
        145.324, 145.324, 145.324],
       [153.456, 153.456, 153.456, 153.456, 153.456, 153.456, 153.456,
        153.456, 153.456, 153.456],
       [144.971, 149.59 , 146.884, 14

## 色域空间转换

In [755]:
def ycbcr_to_rgb(img):
    # Coefficients for conversion from YCbCr to RGB
    xform = np.array([[1.0, 0.0, 1.402],
                      [1.0, -0.344136, -0.714136],
                      [1.0, 1.772, 0.0]])
    
    img[:, :, [1, 2]] -= 128   # Subtracting 128 from Cb and Cr channels
    rgb = img.dot(xform.T)
    return np.uint8(rgb.clip(0, 255))

def upsample_420(y, cb, cr):
    # Downsample the Cb and Cr channels by a factor of 2
    y_un = y
    cb_un = np.repeat(np.repeat(cb, 2, axis=1), 2, axis=0)
    cr_un = np.repeat(np.repeat(cr, 2, axis=1), 2, axis=0)
    result = np.stack([y_un, cb_un, cr_un], axis=-1)  # 将三个数组沿着新轴堆叠起来
    return result
    
def save_array_to_image(image_array, file_path):
    img = Image.fromarray(image_array.astype('uint8'))
    img.save(file_path)

In [756]:
ycbcr_img = upsample_420(y,cb,cr)
rgb_image = ycbcr_to_rgb(ycbcr_img)
file_path = './ganyu_ende.png'  

In [757]:
save_array_to_image(rgb_image, file_path)

In [758]:
rgb_image[0][0]

array([ 9,  7, 19], dtype=uint8)